baseURL = "https://www.inhs.web.id/"
languageCode = "en-us"
title = "I Nyoman Harry Sudana : Personal Website"
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/harrysudana/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/harrysudana/"}
  ]
  
[params]
  layoutReverse = true
  description = "This is personal website's I Nyoman Harry Sudana - Househusband that Write a Code - who live in Badung, Bali, Indonesia"
  themeColor = "theme-base-0f"